import Head from 'next/head'
import Image from 'next/image'
import { Overpass } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import foods from '../data/food_data'
import NavBar from '@/comps/nav'
import Footer from '@/comps/footer'

const overpass = Overpass({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={overpass.className}>
        <NavBar/>
    
          <div className={styles.mainHome}>
            <p>ayo</p>
          
          </div>
      <Footer/>
      </main>
    </>
  )
}
